let user_id = localStorage.getItem("id");
//items in shop
let data = [
  {
    qty: 1,
    id: "1",
    idUser: localStorage.getItem("id") || Date.now(),
    img: "../photo/10.jpg",
    title: "Kids Toy Car Level Break Adventure Toy Blue",
    rate: "",
    price: 1225.28,
    Availability: "12 Left in Stock",
    description:
      "I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.        ",
  },
  {
    qty: 1,
    id: "2",
    idUser: localStorage.getItem("id") || Date.now(),
    img: "../photo/11.jpg",
    title: "Home Supermarket Kids Playset",
    rate: "",
    price: 80,
    Availability: "30 Left in Stock",
    description:
      "I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.        ",
  },
  {
    qty: 1,
    id: "3",
    idUser: localStorage.getItem("id") || Date.now(),
    img: "../photo/12.jpg",
    title: "Baby Phone Toy",
    rate: "",
    price: 90,
    Availability: "11 Left in Stock",
    description:
      "I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.        ",
  },
  {
    qty: 1,
    id: "4",
    idUser: localStorage.getItem("id") || Date.now(),
    img: "../photo/13.jpg",
    title: "Cars & Trucks Toys",
    rate: "",
    price: 1000,
    Availability: "5 Left in Stock",
    description:
      "I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.        ",
  },
  {
    qty: 1,
    id: "5",
    idUser: localStorage.getItem("id") || Date.now(),
    img: "../photo/14.jpg",
    title: "Best Music Gifts for Kids",
    rate: "",
    price: 96,
    Availability: "10 Left in Stock",
    description:
      "I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.        ",
  },
  {
    qty: 1,
    id: "6",
    idUser: localStorage.getItem("id") || Date.now(),
    img: "../photo/15.jpg",
    title: "Baybee Musical Toys",
    rate: "",
    price: 77,
    Availability: "9 Left in Stock",
    description:
      "I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.        ",
  },
  {
    qty: 1,
    id: "7",
    idUser: localStorage.getItem("id") || Date.now(),
    img: "../photo/16.jpg",
    title: "Plastic monster truck",
    rate: "",
    price: 125,
    Availability: "3 Left in Stock",
    description:
      "I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.        ",
  },
  {
    qty: 1,
    id: "8",
    idUser: localStorage.getItem("id") || Date.now(),
    img: "../photo/17.jpg",
    title: "Magical Unicorn ",
    rate: "",
    price: 1225,
    Availability: "8 Left in Stock",
    description:
      "I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.        ",
  },
  {
    qty: 1,
    id: "9",
    idUser: localStorage.getItem("id") || Date.now(),
    img: "../photo/18.jpg",
    title: "Home Supermarket",
    rate: "",
    price: 122,
    Availability: "12 Left in Stock",
    description:
      "I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.        ",
  },
  {
    qty: 1,
    id: "10",
    idUser: localStorage.getItem("id") || Date.now(),
    img: "../photo/19.jpg",
    title: "Toddler Truck",
    rate: "",
    price: 228,
    Availability: "1 Left in Stock",
    description:
      "I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.        ",
  },
  {
    qty: 1,
    id: "11",
    idUser: localStorage.getItem("id") || Date.now(),
    img: "../photo/20.jpg",
    title: "Cutting Fruits Vegetables ",
    rate: "",
    price: 600,
    Availability: "15 Left in Stock",
    description:
      "I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.        ",
  },
  {
    qty: 1,
    id: "12",
    idUser: localStorage.getItem("id") || Date.now(),
    img: "../photo/21.jpg",
    title: "Plastic Ball Drop Toy",
    rate: "",
    price: 122,
    Availability: "17 Left in Stock",
    description:
      "I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.        ",
  },
  {
    qty: 1,
    id: "13",
    idUser: localStorage.getItem("id") || Date.now(),
    img: "../photo/22.jpg",
    title: "Ci Vetch Toys Trucks Cars",
    rate: "",
    price: 1225,
    Availability: "5 Left in Stock",
    description:
      "I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.        ",
  },
  {
    qty: 1,
    id: "14",
    idUser: localStorage.getItem("id") || Date.now(),
    img: "../photo/23.jpg",
    title: " Wooden Hammer Knock",
    rate: "",
    price: 158,
    Availability: "4 Left in Stock",
    description:
      "I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.        ",
  },
  {
    qty: 1,
    id: "15",
    idUser: localStorage.getItem("id") || Date.now(),
    img: "../photo/24.jpg",
    title: " Gourmet Cooking Box Toy",
    rate: "",
    price: 689,
    Availability: "6 Left in Stock",
    description:
      "I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.        ",
  },
  {
    qty: 1,
    id: "16",
    idUser: localStorage.getItem("id") || Date.now(),
    img: "../photo/25.jpg",
    title: "JCB Bulldozer ",
    rate: "",
    price: 758,
    Availability: "7 Left in Stock",
    description:
      "I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.        ",
  },
];
localStorage.setItem("ToyKids", JSON.stringify(data));
let ToyKidsAll = JSON.parse(localStorage.getItem("ToyKids"));
//articles
let blog = [
  {
    idUser: localStorage.getItem("id") || Date.now(),
    id: 1,
    title: "It is a long established fact that a reader will be distracted",
    owner: "ADMIN",
    date: "03/11/2021",
    p1: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage.",
    quote:
      "“Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,”",
    p2: 'and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.',
    img: "../photo/26.jpg",
    no_comment: 0,
  },
  {
    idUser: localStorage.getItem("id") || Date.now(),
    id: 2,
    title: "It is a long established fact that a reader will be distracted",
    owner: "ADMIN",
    date: "03/11/2021",
    p1: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage.",
    quote:
      "“Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,”",
    p2: 'and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.',
    img: "../photo/27.jpg",
    no_comment: 0,
  },
  {
    idUser: localStorage.getItem("id") || Date.now(),
    id: 3,
    title: "It is a long established fact that a reader will be distracted",
    owner: "ADMIN",
    date: "03/11/2021",
    p1: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage.",
    quote:
      "“Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,”",
    p2: 'and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.',
    img: "../photo/28.jpg",
    no_comment: 0,
  },
  {
    idUser: localStorage.getItem("id") || Date.now(),
    id: 4,
    title: "It is a long established fact that a reader will be distracted",
    owner: "ADMIN",
    date: "03/11/2021",
    p1: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage.",
    quote:
      "“Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,”",
    p2: 'and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.',
    img: "../photo/29.jpg",
    no_comment: 0,
  },
  {
    idUser: localStorage.getItem("id") || Date.now(),
    id: 5,
    title: "It is a long established fact that a reader will be distracted",
    owner: "ADMIN",
    date: "03/11/2021",
    p1: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage.",
    quote:
      "“Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,”",
    p2: 'and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.',
    img: "../photo/30.jpg",
    no_comment: 0,
  },
  {
    idUser: localStorage.getItem("id") || Date.now(),
    id: 6,
    title: "It is a long established fact that a reader will be distracted",
    owner: "ADMIN",
    date: "03/11/2021",
    p1: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage.",
    quote:
      "“Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,”",
    p2: 'and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.',
    img: "../photo/31.jpg",
    no_comment: 0,
  },
  {
    idUser: localStorage.getItem("id") || Date.now(),
    id: 7,
    title: "It is a long established fact that a reader will be distracted",
    owner: "ADMIN",
    date: "03/11/2021",
    p1: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage.",
    quote:
      "“Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,”",
    p2: 'and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.',
    img: "../photo/32.jpg",
    no_comment: 0,
  },
  {
    idUser: localStorage.getItem("id") || Date.now(),
    id: 8,
    title: "It is a long established fact that a reader will be distracted",
    owner: "ADMIN",
    date: "03/11/2021",
    p1: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage.",
    quote:
      "“Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,”",
    p2: 'and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.',
    img: "../photo/33.jpg",
    no_comment: 0,
  },
  {
    idUser: localStorage.getItem("id") || Date.now(),
    id: 9,
    title: "It is a long established fact that a reader will be distracted",
    owner: "ADMIN",
    date: "03/11/2021",
    p1: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage.",
    quote:
      "“Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,”",
    p2: 'and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.',
    img: "../photo/32.jpg",
    no_comment: 0,
  },
];
localStorage.setItem("blog", JSON.stringify(blog));
blog = JSON.parse(localStorage.getItem("blog"));
